### PR TITLE
Make compilation of Contact library independent from Planners library

### PR DESCRIPTION
**Pull request by prashanthr05**

### CODE REVIEW

**Review by S-Dafarra — APPROVED** [review]
Should something be added to the changelog?

**Comment by prashanthr05** [comment]
> Should something be added to the changelog?

If we are going to add specifically about `Contact` library on the README, then I guess it makes sense to update also the CHANGELOG. Otherwise, I think it's safe to ignore it.

**Comment by S-Dafarra** [comment]
> > Should something be added to the changelog?
> 
> If we are going to add specifically about `Contact` library on the README, then I guess it makes sense to update also the CHANGELOG. Otherwise, I think it's safe to ignore it.

As you prefer.

**Comment by prashanthr05** [comment]
Actually
> Implement Contact library. (https://github.com/dic-iit/bipedal-locomotion-framework/pull/43 and https://github.com/dic-iit/bipedal-locomotion-framework/pull/45)

This line already exists in the CHANGELOG. Since we are yet to release a new version, I think we can stick with the default.

**Review by GiulioRomualdi — APPROVED** [review]

**Comment by GiulioRomualdi** [comment]
Let me know if I can merge it

**Comment by prashanthr05** [comment]
@GiulioRomualdi please see the discussion here https://github.com/dic-iit/bipedal-locomotion-framework/pull/142#discussion_r522823899.
We need to consider that design decision before merging this.

**Comment by prashanthr05** [comment]
Give the comment in https://github.com/dic-iit/bipedal-locomotion-framework/pull/142#discussion_r522824832, we could proceed with the merge.

**Comment by prashanthr05** [comment]
Sorry I mistakenly clicked on `Close with comment` instead of `comment` ;D

**Comment by S-Dafarra** [comment]
We can merge this, right?

**Review by GiulioRomualdi — APPROVED** [review]
Feel free to merge

**Comment by prashanthr05** [comment]
Thanks for the merge.

**Pull request merged**
