### PR TITLE
Migrate ContactDetectors into Contacts folder

### PR DESCRIPTION
**Pull request by prashanthr05**
- ContactDetectors moved from `Estimators` folder into `Contacts` folder
- Previously existing tests in `Contacts/tests` moved into `Contacts/tests/Contacts` while ContactDetector tests moved into `Contacts/tests/ContactDetectors`.

### CODE REVIEW

**Comment by prashanthr05** [comment]
I forgot to change the namespaces.

**Comment by prashanthr05** [comment]
> I forgot to change the namespaces.

Fixed in https://github.com/dic-iit/bipedal-locomotion-framework/pull/209/commits/786263be13867aabadc66985e7c3a02d5635b6ef

**Review by GiulioRomualdi — COMMENTED** [review]
Could you please update the include guards? 
E.g. `BIPEDAL_LOCOMOTION_SCHMITT_TRIGGER_DETECTOR_H` -> `BIPEDAL_LOCOMOTION_CONTACT_DETECTORS_SCHMITT_TRIGGER_DETECTOR_H`

**Comment by prashanthr05** [comment]
> Could you please update the include guards?
> E.g. `BIPEDAL_LOCOMOTION_SCHMITT_TRIGGER_DETECTOR_H` -> `BIPEDAL_LOCOMOTION_CONTACT_DETECTORS_SCHMITT_TRIGGER_DETECTOR_H`

Done in https://github.com/dic-iit/bipedal-locomotion-framework/pull/209/commits/c99eda6c0e2581637119ef586c92288faa8e6ba8

**Comment by GiulioRomualdi** [comment]
Super! Let me know if you want to reorganize the commits otherwise, I will merge

**Review by GiulioRomualdi — APPROVED** [review]

**Comment by prashanthr05** [comment]
Thanks @GiulioRomualdi ! I have squashed and rebased the commits.

**Pull request merged**
