### PR TITLE
Update IK and TSID to the latest manif version

### LINKED ISSUE #235: Make the repo working with the latest version of manif
Required after https://github.com/artivis/manif/pull/190

```
home/gromualdi/robot-code/robotology-superbuild/src/bipedal-locomotion-framework/src/TSID/src/SE3Task.cpp: In member function ‘bool BipedalLocomotion::TSID::SE3Task::setReferenceTrajectory(const SE3d&, const Tangent&, const Tangent&)’:
/home/gromualdi/robot-code/robotology-superbuild/src/bipedal-locomotion-framework/src/TSID/src/SE3Task.cpp:149:83: error: ‘const Tangent’ {aka ‘const struct manif::SE3Tangent<double>’} has no member named ‘v’
  149 |     ok = ok && m_R3Controller.setDesiredState({I_H_F.translation(), mixedVelocity.v()});
      |                                                                                   ^
/home/gromualdi/robot-code/robotology-superbuild/src/bipedal-locomotion-framework/src/TSID/src/SE3Task.cpp:149:87: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘const State&’ {aka ‘const std::tuple<manif::Rn<double, 3>, manif::RnTangent<double, 3> >&’}
  149 |     ok = ok && m_R3Controller.setDesiredState({I_H_F.translation(), mixedVelocity.v()});
      |                                                                                       ^
In file included from /home/gromualdi/robot-code/robotology-superbuild/build/install/include/LieGroupControllers/impl/ProportionalDerivativeController/Controller.h:15,
                 from /home/gromualdi/robot-code/robotology-superbuild/build/install/include/LieGroupControllers/ProportionalDerivativeController.h:11,
                 from /home/gromualdi/robot-code/robotology-superbuild/src/bipedal-locomotion-framework/src/TSID/include/BipedalLocomotion/TSID/SE3Task.h:15,
                 from /home/gromualdi/robot-code/robotology-superbuild/src/bipedal-locomotion-framework/src/TSID/src/SE3Task.cpp:8:
/home/gromualdi/robot-code/robotology-superbuild/build/install/include/LieGroupControllers/impl/ProportionalDerivativeController/ControllerBase.h:87:83: note:   initializing argument 1 of ‘bool LieGroupControllers::ProportionalDerivativeControllerBase<_Derived>::setDesiredState(const State&) [with _Derived = LieGroupControllers::ProportionalDerivativeController<manif::Rn<double, 3> >; LieGroupControllers::ProportionalDerivativeControllerBase<_Derived>::State = std::tuple<manif::Rn<double, 3>, manif::RnTangent<double, 3> >]’
   87 | bool ProportionalDerivativeControllerBase<_Derived>::setDesiredState(const State& state)
      |                                                                      ~~~~~~~~~~~~~^~~~~
/home/gromualdi/robot-code/robotology-superbuild/src/bipedal-locomotion-framework/src/TSID/src/SE3Task.cpp:150:64: error: ‘const Tangent’ {aka ‘const struct manif::SE3Tangent<double>’} has no member named ‘v’
  150 |     ok = ok && m_R3Controller.setFeedForward(mixedAcceleration.v());
      |                                                                ^
/home/gromualdi/robot-code/robotology-superbuild/src/bipedal-locomotion-framework/src/TSID/src/SE3Task.cpp:152:77: error: ‘const Tangent’ {aka ‘const struct manif::SE3Tangent<double>’} has no member named ‘w’
  152 |     ok = ok && m_SO3Controller.setDesiredState({I_H_F.quat(), mixedVelocity.w()});
      |                                                                             ^
/home/gromualdi/robot-code/robotology-superbuild/src/bipedal-locomotion-framework/src/TSID/src/SE3Task.cpp:152:81: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘const State&’ {aka ‘const std::tuple<manif::SO3<double>, manif::SO3Tangent<double> >&’}
  152 |     ok = ok && m_SO3Controller.setDesiredState({I_H_F.quat(), mixedVelocity.w()});
      |                                                                                 ^
In file included from /home/gromualdi/robot-code/robotology-superbuild/build/install/include/LieGroupControllers/impl/ProportionalDerivativeController/Controller.h:15,
                 from /home/gromualdi/robot-code/robotology-superbuild/build/install/include/LieGroupControllers/ProportionalDerivativeController.h:11,
                 from /home/gromualdi/robot-code/robotology-superbuild/src/bipedal-locomotion-framework/src/TSID/include/BipedalLocomotion/TSID/SE3Task.h:15,
                 from /home/gromualdi/robot-code/robotology-superbuild/src/bipedal-locomotion-framework/src/TSID/src/SE3Task.cpp:8:
/home/gromualdi/robot-code/robotology-superbuild/build/install/include/LieGroupControllers/impl/ProportionalDerivativeController/ControllerBase.h:87:83: note:   initializing argument 1 of ‘bool LieGroupControllers::ProportionalDerivativeControllerBase<_Derived>::setDesiredState(const State&) [with _Derived = LieGroupControllers::ProportionalDerivativeController<manif::SO3<double> >; LieGroupControllers::ProportionalDerivativeControllerBase<_Derived>::State = std::tuple<manif::SO3<double>, manif::SO3Tangent<double> >]’
   87 | bool ProportionalDerivativeControllerBase<_Derived>::setDesiredState(const State& state)
      |                                                                      ~~~~~~~~~~~~~^~~~~
/home/gromualdi/robot-code/robotology-superbuild/src/bipedal-locomotion-framework/src/TSID/src/SE3Task.cpp:153:65: error: ‘const Tangent’ {aka ‘const struct manif::SE3Tangent<double>’} has no member named ‘w’
  153 |     ok = ok && m_SO3Controller.setFeedForward(mixedAcceleration.w());
      |                                                                 ^
make[2]: *** [src/TSID/CMakeFiles/TSID.dir/build.make:76: src/TSID/CMakeFiles/TSID.dir/src/SE3Task.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3077: src/TSID/CMakeFiles/TSID.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
This fixes #235.

@traversaro while merging this PR we should update the version of installed manif in superbuild and in conda.

We may probably ask to add a tag in manif

### CODE REVIEW

**Comment by traversaro** [comment]
Just to understand, there is any specific reason for updating now? Could it make sense to wait for the next release/tag of manif, and then update after it?

**Comment by GiulioRomualdi** [comment]
The latest version of manif introduces python bindings that can be used in blf as shown in https://github.com/dic-iit/bipedal-locomotion-framework/pull/238#issuecomment-799435166

**Comment by traversaro** [comment]
> 
> 
> Just to understand, there is any specific reason for updating now? Could it make sense to wait for the next release/tag of manif, and then update after it?

Ok, I suspect the answer is related to https://github.com/dic-iit/bipedal-locomotion-framework/pull/238#issuecomment-799435166 .

**Comment by traversaro** [comment]
> 
> 
> The latest version of manif introduces python bindings that can be used in blf as shown in [#238 (comment)](https://github.com/dic-iit/bipedal-locomotion-framework/pull/238#issuecomment-799435166)

I think I replied exactly at the same time.

**Comment by traversaro** [comment]
Ok for superbuild, for conda unfortunately we need to wait for a release (not a problem until we tag a new release of blf).

**Comment by traversaro** [comment]
> 
> 
> Ok for superbuild, for conda unfortunately we need to wait for a release (not a problem until we tag a new release of blf).

Note that this probably means that we either shut down the conda CI, or we just install manif manually there.

**Comment by GiulioRomualdi** [comment]
> Note that this probably means that we either shut down the conda CI, or we just install manif manually there.

I think we can manually install manif there

**Comment by GiulioRomualdi** [comment]
Let's wait for https://github.com/artivis/manif/pull/211 before changing the Conda CI and merge the PR

**Comment by GiulioRomualdi** [comment]
In https://github.com/dic-iit/bipedal-locomotion-framework/pull/239/commits/3c1ec669a36c533093732d617749f87e03c34231 I manually installed `manif` But I'm not actually sure that it will be installed in a "visible" location

**Comment by traversaro** [comment]
> 
> 
> In [3c1ec66](https://github.com/dic-iit/bipedal-locomotion-framework/commit/3c1ec669a36c533093732d617749f87e03c34231) I manually installed `manif` But I'm not actually sure that it will be installed in a "visible" location

I fixed the problem, the "system" C++ prefixes for conda environments are `${CONDA_PREFIX}` on Linux/macOS and `${CONDA_PREFIX}/Library` on Windows. I have an idea on how to clean this user experience, but I need to suggest an modification in CMake upstream and this could take time.

**Review by traversaro — APPROVED** [review]

**Pull request merged**
