### PR TITLE
Update vcpkg_robotology_TAG in CI.yml

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
Hopefully, this will fix https://github.com/dic-iit/bipedal-locomotion-framework/runs/3124956581?check_suite_focus=true

### CODE REVIEW

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
At this point, for me it is ok if you want to drop the vcpkg-based Windows build, as it seems to me that the future is conda-oriented.

**Comment by traversaro** [comment]
Probably related to https://github.com/actions/virtual-environments/issues/3742, it seems that old vcpkg crashes with the newest CMake.

**Comment by traversaro** [comment]
> 
> 
> Probably related to [actions/virtual-environments#3742](https://github.com/actions/virtual-environments/issues/3742), it seems that old vcpkg crashes with the newest CMake.

Related comment; https://github.com/microsoft/vcpkg/issues/18952#issuecomment-881787892 .

**Comment by GiulioRomualdi** [comment]
Even if I bumped the vcpkg robotology  version  to 0.7.0, vcpkg still crashes 
@traversaro

**Comment by traversaro** [comment]
> Even if I bumped the vcpkg robotology version to 0.7.0, vcpkg still crashes
> @traversaro

I tried to re-bootstrap it, to see if it fixes something (but to be honest it is quite a blind attempt).

**Comment by traversaro** [comment]
Doing the bootstrap was working, but then we hitted again https://github.com/microsoft/vcpkg/issues/15836 . However, to avoid problem related to that it was sufficint to explicitly pass the overlay-ports option.

**Comment by GiulioRomualdi** [comment]
It's working! Thank you @traversaro

**Pull request merged**
