### PR TITLE
General update of the GitHub CI

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
This PR:
1. Drop the GitHub CI on ubuntu 18.04
2. Now the python packages are installed from apt in CI
3. Check the compilation if one of the dependency is missing

### CODE REVIEW

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
The failures seems to be stuff that was untested in Ubuntu 20.04 .

**Comment by GiulioRomualdi** [comment]
https://github.com/dic-iit/bipedal-locomotion-framework/pull/173/commits/7976c0b25bbf98a167c9c1e968f655435712121e partially fixes https://github.com/dic-iit/bipedal-locomotion-framework/issues/163

**Comment by GiulioRomualdi** [comment]
There Seems that `PythonBindingsUnitTest` is not compiled anymore

**Comment by GiulioRomualdi** [comment]
I updated the first comment https://github.com/dic-iit/bipedal-locomotion-framework/pull/173#issue-561038477, @Traversaro let me know if you are still fine with the PR :smile:

**Review by traversaro — APPROVED** [review]

**Pull request merged**
