### PR TITLE
conda CI: Use CasADi>=3.5.5 to avoid that an old CasADi without ipopt is picked by the conda solver

### PR DESCRIPTION
**Pull request by traversaro**
Local fix for https://github.com/dic-iit/bipedal-locomotion-framework/issues/353 . I will do the proper fix at the casadi-feedstock level, but for the time being this should work fine.

### CODE REVIEW

**Comment by traversaro** [comment]
@GiulioRomualdi I think we can avoid to modify the changelog for this CI-related fixes, what do you think?

**Comment by GiulioRomualdi** [comment]
> @GiulioRomualdi I think we can avoid to modify the changelog for this CI-related fixes, what do you think?

I agree :)

**Review by GiulioRomualdi — APPROVED** [review]

**Comment by GiulioRomualdi** [comment]
The problem seems to be still there

**Comment by traversaro** [comment]
> 
> 
> The problem seems to be still there

I forgot the quotes in the command, now it should be fine.

**Review by GiulioRomualdi — APPROVED** [review]

**Comment by GiulioRomualdi** [comment]
Super! Thank you @traversaro

**Pull request merged**
