### PR TITLE
Add USE_MATH_DEFINES for tests and library compile definitions

### PR DESCRIPTION
**Pull request by prashanthr05**
See https://github.com/dic-iit/bipedal-locomotion-framework/pull/85#issuecomment-686605967

### CODE REVIEW

**Comment by S-Dafarra** [comment]
I don't remember. Was this definition useful only for executables? Does it make sense also to add this definition for the libraries?

**Comment by prashanthr05** [comment]
> I don't remember. Was this definition useful only for executables? Does it make sense also to add this definition for the libraries?


I think it makes sense for libraries as well. In general, anything that would pertain the using math constants.

**Review by S-Dafarra — APPROVED** [review]

**Comment by prashanthr05** [comment]
I made a mistake in copy-paste ;D and another mistake of not building before pushing.

Anyways, shall we also add the definitions for interface?

**Comment by S-Dafarra** [comment]
> I made a mistake in copy-paste ;D and another mistake of not building before pushing.
> 
> Anyways, shall we also add the definitions for interface?

And I did not notice it :joy: In theory, interface targets are not built. So it should be handled by user classes I guess :thinking:

**Comment by prashanthr05** [comment]
> And I did not notice it In theory, interface targets are not built. So it should be handled by user classes I guess 

Alright. we shall add those definitions only for libraries then.

**Review by GiulioRomualdi — APPROVED** [review]
Merging! Thank you @prashanthr05

**Pull request merged**
