### PR TITLE
CI: Refresh dependencies versions 

### PR DESCRIPTION
**Pull request by traversaro**
Obviously if there is a failure we will not be 100% sure of what caused it, but we are like the [Steve McQueen](https://en.wikipedia.org/wiki/Steve_McQueen) of CI and so we like to live like this.

### CODE REVIEW

**Comment by traversaro** [comment]
I disabled the changelog check as I think that this is an internal CI change that is not interesting for downstream users, let me know if you think otherwise @GiulioRomualdi .

**Comment by traversaro** [comment]
Apparently vcpkg-robotology 0.6.1 has a regression, probably related to vcpkg : 
~~~
2021-02-04T11:52:43.8649643Z Read more about vcpkg telemetry at docs/about/privacy.md
2021-02-04T11:52:45.0181804Z Error getting canonicalization of C:/robotology/robotology-vcpkg-binary-ports: The system cannot find the file specified.
2021-02-04T11:52:45.0822841Z Error getting canonicalization of C:/robotology/robotology-vcpkg-binary-ports: The system cannot find the file specified.
2021-02-04T11:52:45.1654158Z ##[error]Process completed with exit code 1.
2021-02-04T11:52:45.1979109Z Post job cleanup.
~~~

**Comment by traversaro** [comment]
vcpkg change reverted in https://github.com/dic-iit/bipedal-locomotion-framework/pull/190/commits/fbb4d2f176b9b68e8ca93d5b2a399dca8bca092f .

**Comment by traversaro** [comment]
Beside the vcpkg, all the other bumps seems to work fine. @GiulioRomualdi @prashanthr05 @S-Dafarra

**Comment by GiulioRomualdi** [comment]
Thank you @traversaro!! Merging!

**Pull request merged**
