### PR TITLE
Add the possibility to disable the proportional controller in the IK::SE3Task

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
This PR adds the possibility to disable/enable the LieGroup controller in the `IK::SE3Task`. 

This feature is useful when the task is used to control the foot. Indeed when the foot is in contact with the ground the desired cartesian velocity should be fixed to zero.

As far as I know, @paolo-viceconte needed this feature to obtain successful results in his test. This PR give a better structure to the feature. 

This PR depends on https://github.com/dic-iit/lie-group-controllers/pull/9

### CODE REVIEW

**Comment by GiulioRomualdi** [comment]
I forgot to push a fie. Now the PR is ready to be reviewed

**Comment by traversaro** [comment]
I am a bit confused by the `setControlState`/`getControlState` naming of the methods. If I understood correctly, this API will permit to disable the "star trick" controller, and directly specify the desired value for the task. If you are disabling the controller, what it does mean to set its state? Furthermore, the PD controller tipically used by "star trick" are state-less controllers, so it is not clear what it does mean to set its state. Perhaps we could call that the "Task Input", and document that the "Task Input" can either be computed automatically with a PD controller that computes this value from position and velocity feedback of some kind, or provided directly. 

Also a few lines of examples of use of this API (or even modifying the scheme we did some time ago, and I don't remember if it is somewhere in docs).

**Comment by traversaro** [comment]
Also, having a normal name for "start trick" controller to use in docs and issue/PRs would be probably useful, not sure if anyone has any good idea on this. fyi @DanielePucci

**Comment by traversaro** [comment]
> (or even modifying the scheme we did some time ago, and I don't remember if it is somewhere in docs

Found it: https://dic-iit.github.io/bipedal-locomotion-framework/classBipedalLocomotion_1_1IK_1_1IntegrationBasedIK.html#vc . I think after this PR that scheme is outdated, we don't need to update it now but I would open an issue to eventually update it.

**Comment by traversaro** [comment]
> 
> 
> Also, having a normal name for "start trick" controller to use in docs and issue/PRs would be probably useful, not sure if anyone has any good idea on this. The words that we use tipically influence how clear we have in mind a subject, especially for new comers (see https://www.youtube.com/watch?v=oQ1WIxtylGc). fyi @DanielePucci

In https://dic-iit.github.io/bipedal-locomotion-framework/classBipedalLocomotion_1_1IK_1_1IntegrationBasedIK.html#vc we called it "Task Level Controller", probably we can consider that naming.

**Comment by DanielePucci** [comment]
> Also, having a normal name for "start trick" controller to use in docs and issue/PRs would be probably useful, not sure if anyone has any good idea on this. 

I agree on this, a possibility could be that of referring to the quantity set by the "star trick". Often, it is a sort of "desired acceleration", or velocity, that stabilises the task towards the desired value. Calling them "desired velocity/acceleration", however, would create the confusion between the actual desired quantities and those that the controller has to achieve to stabilize the desired quantity itself.

So, more precisely, the star trick refers to shape of the closed loop dynamics that the control input should impose. A possibility then could be that of calling it something like `closed-loop-[quantity]`, e.g `closed-loop-acceleration` or `closed-loop-velocity`, or more generally `closed-loop-dynamics`

> The words that we use tipically influence how clear we have in mind a subject, especially for new comers (see https://www.youtube.com/watch?v=oQ1WIxtylGc). fyi @DanielePucci

In this respect, there is a nice quote I like by Ambrose Bierce, author of the book [Write It Right, a Little Blacklist of Literary Faults](https://www.amazon.com/Write-Little-Blacklist-Literary-Faults/dp/1340214768/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=&sr=) that is

> Clear writing is clear thinking made visible.

**Comment by GiulioRomualdi** [comment]
After a F2F discussion with @traversaro we decided to apply the following modification to [this class](https://github.com/dic-iit/bipedal-locomotion-framework/blob/12a648707cca386cf572f08108ed8c5f26be7502/src/System/include/BipedalLocomotion/System/ControlTask.h#L20):
1 `ControlTask` -> `ITaskControllerManager`
2. `State` -> `Mode` 
3. `setControlState` -> `setTaskControllerMode`
4. `getControlState` -> `getTaskControllerMode`

**Review by traversaro — APPROVED** [review]

**Comment by GiulioRomualdi** [comment]
As usual vcpkg fails but @traversaro is on it

**Comment by traversaro** [comment]
> 
> 
> After a F2F discussion with @traversaro we decided to apply the following modification to [this class](https://github.com/dic-iit/bipedal-locomotion-framework/blob/12a648707cca386cf572f08108ed8c5f26be7502/src/System/include/BipedalLocomotion/System/ControlTask.h#L20):
> 1 `ControlTask` -> `ITaskControllerManager`
> 2. `State` -> `Mode`
> 3. `setControlState` -> `setTaskControllerMode`
> 4. `getControlState` -> `getTaskControllerMode`

To elaborate a bit more on this choice: an instantaneous PD controller in which the actual feedback can be enable or disabled, while the feedforward parts remains, it is effectively a hybrid system, in which there is no continuous state as the output is a function of the input, but with a discrete state that is a boolean variable that indicates if the feedback is active or not. As the "discrete state" in hybrid system is often also called "mode", that was the rationale to use "mode" instead of "state".

**Pull request merged**
