### PR TITLE
Move LinearTask in System component 

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
This PR moves the `LinearTask` in system component. Discussing with @S-Dafarra we decided to remove `setKinDyn()` and `initialize` from the `LinearTask`. We also decided to add `isValid()` to check if the content of `getA()` and `getB()` are valid.

This PR removes also the `Task` in TSID. Now all the tasks in IK and TSID inherits from `System::LinearTask`

cc @isorrentino

### CODE REVIEW

**Comment by traversaro** [comment]
In which header is now `LinearTask.h` defined? I can't find it.

**Comment by traversaro** [comment]
> 
> 
> In which header is now `LinearTask.h` defined? I can't find it.

The CI seems to agree. :D

**Comment by GiulioRomualdi** [comment]
My fault. I forgot to commit the file. Done in  16e96b0dcb9a33589abb79fff3e2228bc8a3967e

**Comment by GiulioRomualdi** [comment]
`brew`, I :heart: you 

```
Error: Failed to download resource "sqlite"
Download failed: https://homebrew.bintray.com/bottles/sqlite-3.34.1.catalina.bottle.tar.gz
```

**Review by S-Dafarra — APPROVED** [review]

**Comment by S-Dafarra** [comment]
I wonder whether it could make sense to check that every task is valid when solving the IK :thinking:

**Comment by GiulioRomualdi** [comment]
> I wonder whether it could make sense to check that every task is valid when solving the IK 🤔

Yes I add a check

**Pull request merged**
