### PR TITLE
Make the `joints_list` parameter as optional in the YarpSensorBridge

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
This fixes the point 2 of #121 

I tested with the `YarpDevice` implemented by @prashanthr05

### CODE REVIEW

**Review by prashanthr05 — APPROVED** [review]
Minor comment! Otherwise, LGTM.

**Comment by prashanthr05** [comment]
Could you also add a comment in the Doxygen describing the order?

**Comment by GiulioRomualdi** [comment]
In https://github.com/dic-iit/bipedal-locomotion-framework/pull/123/commits/ac3121b95a916b814af35317b04fdf59e83e73fd I also updated the documentation related to #122

**Comment by prashanthr05** [comment]
Great, thanks! I approve of the changes! Let's wait for the CI to pass before merging!

**Pull request merged**
