### PR TITLE
Implement YarpParametersHandler bindings

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
This PR implements the python bindings for the `YarpParametersHandler` class. 

It is possible to load the parameters directly from the configuration file thanks to `set_from_file` method. While writing the tests I noticed a bug in the `setParameter` method for the `YarpParametersHandler` #308. I think this is te reason why the test is failing:
```
40: =================================== FAILURES ===================================
40: __________________________________ test_bool ___________________________________
40: 
40:     def test_bool():
40:     
40:         handler = blf.YarpParametersHandler()
40:     
40:         handler.set_parameter_bool(name="my_bool", value=True)
40:     
40: >       assert handler.get_parameter_bool(name="my_bool") is True
40: E       ValueError: Failed to find a parameter that matches the type
40: 
40: ../../../src/bipedal-locomotion-framework/bindings/python/ParametersHandler/tests/test_parameters_handler_yarp.py:13: ValueError
40: ----------------------------- Captured stdout call -----------------------------
40: [2021-05-24 16:37:43.244] [thread: 80274] [blf] [error] [BipedalLocomotion::YarpUtilities::getElementFromSearchable] The value named: my_bool is not a bool.
40: _______________________________ test_vector_bool _______________________________
40: 
40:     def test_vector_bool():
40:     
40:         handler = blf.YarpParametersHandler()
40:     
40:         handler.set_parameter_vector_bool(name="my_vector_bool",value= [True, False, True])
40:     
40:         assert handler.get_parameter_vector_bool(name="my_vector_bool") == [True, False, True]
40:     
40:         with pytest.raises(ValueError):
40: >           handler.get_parameter_vector_int(name="my_vector_bool")
40: E           Failed: DID NOT RAISE <class 'ValueError'>
40: 
40: ../../../src/bipedal-locomotion-framework/bindings/python/ParametersHandler/tests/test_parameters_handler_yarp.py:88: Failed
40: _______________________________ test_vector_int ________________________________
40: 
40:     def test_vector_int():
40:     
40:         handler = blf.YarpParametersHandler()
40:     
40:         handler.set_parameter_vector_int(name="my_vector_int", value=[-1, 2, 10])
40:     
40:         assert handler.get_parameter_vector_int(name="my_vector_int") == [-1, 2, 10]
40:     
40:         with pytest.raises(ValueError):
40: >           handler.get_parameter_vector_bool(name="my_vector_int")
40: E           Failed: DID NOT RAISE <class 'ValueError'>
```

### CODE REVIEW

**Review by diegoferigo — APPROVED** [review]
Overall the PR looks good to me :+1: I didn't catch anything off.

**Comment by GiulioRomualdi** [comment]
https://github.com/dic-iit/bipedal-locomotion-framework/pull/311 should fix the error in the tests

**Comment by GiulioRomualdi** [comment]
#312 should fix the last bug

**Comment by GiulioRomualdi** [comment]
> #312 should fix the last bug

**Comment by GiulioRomualdi** [comment]
CI failure is now related to `librealsense` https://github.com/IntelRealSense/librealsense/issues/9102

**Comment by GiulioRomualdi** [comment]
Failure fixed in https://github.com/dic-iit/bipedal-locomotion-framework/pull/314

**Pull request merged**
